const express = require('express')
const passport = require('passport')
const authMiddlewares = require('authentication/middlewares')
const api = require('apps/admin/api')

var admin = express.Router()

admin.get('/csrf', (req, res) => {
  res.json({ csrfToken: req.csrfToken() })
})

admin.get('/', authMiddlewares.ensureAuthAdmin, (req, res) => {
  res.render('admin/admin')
})

admin.get('/login', (req, res) => {
  // handle the error generated by the LocalStrategy
  if (req.flash().error) {
    res.status(401).send(req.flash())
  } else {
    res.render('admin/login', { csrfToken: req.csrfToken() })
  }
})

admin.post(
'/login',
passport.authenticate(
  'local',
  { failureRedirect: '/admin/login', failureFlash: true }
),
(req, res) => {
  res.sendStatus(200)
})

// Resources endpoints
admin.use('/api', authMiddlewares.ensureIsSuperUser, api)

module.exports = admin
