FROM node:6.9.1
MAINTAINER sezzhltd@gmail.com

EXPOSE 3000
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY ./web-platform/package.json /usr/src/app
RUN npm install
COPY ./web-platform /usr/src/app

CMD ["npm", "start"]
