FROM python:3.5.2
MAINTAINER sezzhltd@gmail.com

EXPOSE 5000
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY ./auth-service/requirements.txt /usr/src/app
RUN pip install -r /usr/src/app/requirements.txt
COPY ./auth-service /usr/src/app

CMD ["python", "/usr/src/app/runserver.py"]
