FROM node:6.7.0
MAINTAINER sezzhltd@gmail.com

EXPOSE 3000
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY ./nodeapp/package.json /usr/src/app
RUN npm install
COPY ./nodeapp /usr/src/app

CMD ["npm", "start"]
